services:
  kafka:
    image: confluentinc/cp-kafka:7.9.0
    hostname: kafka
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test: kafka-topics --bootstrap-server kafka:29092 --list
      interval: 10s
      timeout: 5s
      retries: 5

  warehouse-service:
    build:
      context: .
      dockerfile: warehouse-service/Dockerfile
    container_name: warehouse-service
    ports:
      - "3344:3344/udp"
      - "3355:3355/udp"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      WAREHOUSE_ID: warehouse-1
    depends_on:
      kafka:
        condition: service_healthy

  central-monitoring-service:
    build:
      context: .
      dockerfile: central-monitoring-service/Dockerfile
    container_name: central-monitoring-service
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      THRESHOLD_TEMPERATURE: "35.0"
      THRESHOLD_HUMIDITY: "50.0"
    depends_on:
      kafka:
        condition: service_healthy
